// Gemini CLI Test Output - Simple Task 0 Test
// Generated by: gemini -m "gemini-2.5-flash"
// Result: SUCCESS - Gemini can generate JavaScript code!

// Full path: Test_BBS_API.js

window.bbs = {
  getUserInfo() {
    return new Promise((resolve, reject) => {
      const messageId = `getUserInfo-${Date.now()}`;
      const handler = (event) => {
        if (event.data.type === 'bbs_response' && event.data.id === messageId) {
          window.removeEventListener('message', handler);
          if (event.data.success) {
            resolve(event.data.payload);
          } else {
            reject(new Error(event.data.error || 'Unknown error'));
          }
        }
      };
      window.addEventListener('message', handler);
      window.parent.postMessage({
        type: 'bbs_request',
        method: 'getUserInfo',
        id: messageId
      }, '*');
    });
  },

  getAppletInfo() {
    return new Promise((resolve, reject) => {
      const messageId = `getAppletInfo-${Date.now()}`;
      const handler = (event) => {
        if (event.data.type === 'bbs_response' && event.data.id === messageId) {
          window.removeEventListener('message', handler);
          if (event.data.success) {
            resolve(event.data.payload);
          } else {
            reject(new Error(event.data.error || 'Unknown error'));
          }
        }
      };
      window.addEventListener('message', handler);
      window.parent.postMessage({
        type: 'bbs_request',
        method: 'getAppletInfo',
        id: messageId
      }, '*');
    });
  }
};

(async () => {
  try {
    console.log("Calling window.bbs.getUserInfo()...");
    const userInfo = await window.bbs.getUserInfo();
    console.log("User Info:", userInfo);

    console.log("Calling window.bbs.getAppletInfo()...");
    const appletInfo = await window.bbs.getAppletInfo();
    console.log("Applet Info:", appletInfo);
  } catch (error) {
    console.error("An error occurred:", error);
  }
})();
