# Generated by Django 5.0.6 on 2025-09-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='handles_mime_types',
            field=models.CharField(blank=True, help_text='Comma-separated list of MIME types this applet can view (e.g., image/png,image/jpeg)', max_length=255),
        ),
    ]
