# Generated by Django 5.0.6 on 2025-10-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_fileattachment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for agent-specific parameters (e.g., poll intervals).'),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_service_path',
            field=models.CharField(blank=True, help_text='Full Python path to the agent service class (e.g., applets.chat_agent_service.ChatAgentService)', max_length=255, null=True),
        ),
    ]
