# Generated by Django 5.0.6 on 2025-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_agent_parameters_user_agent_service_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
