# Generated by Django 5.0.6 on 2025-10-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField(unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'aliases',
            },
        ),
        migrations.CreateModel(
            name='BannedPubkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField(unique=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If the ban is temporary, this is when it expires.', null=True)),
                ('federated_action_id', models.UUIDField(blank=True, help_text='The ID of the federated action that created this ban.', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredPubkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField()),
            ],
        ),
    ]
