# Generated by Django 5.0.6 on 2025-10-02 22:25

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_access_level', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=core.models.get_default_expires_at, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('pubkey', models.TextField(blank=True, null=True)),
                ('metadata_manifest', models.JSONField(blank=True, help_text='BitSync manifest for P2P content distribution.', null=True)),
                ('agent_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_moderated_at', models.DateTimeField(blank=True, help_text='Timestamp of the last moderation action on this message.', null=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='messages', to='core.fileattachment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.message')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.messageboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=core.models.get_default_expires_at, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('sender_pubkey', models.TextField(blank=True, null=True)),
                ('metadata_manifest', models.JSONField(blank=True, help_text='BitSync manifest for BBS-level metadata.', null=True)),
                ('e2e_encrypted_content', models.TextField(blank=True, help_text='The end-to-end encrypted message body and subject.', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_mail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
