# Generated by Django 5.0.6 on 2025-10-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='federation_room_id',
            field=models.CharField(blank=True, help_text="Shared room identifier for federated real-time boards (e.g., 'global-chat'). Multiple BBS instances use the same room_id to sync messages in real-time.", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='is_realtime',
            field=models.BooleanField(default=False, help_text='Enable real-time federation sync for low-latency updates. When True, messages bypass BitSync polling and use direct BBS-to-BBS push (1s poll interval).'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='message_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='Number of days to retain messages before automatic expiration. Real-time boards typically use 1 day, regular boards use 30 days.'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='trusted_peers',
            field=models.JSONField(blank=True, default=list, help_text="List of trusted peer onion URLs for real-time sync. Format: ['http://peer1.onion', 'http://peer2.onion']. Only applies when is_realtime=True."),
        ),
    ]
