# Generated by Django 5.0.6 on 2025-11-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageboard_federation_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='federation_poll_interval',
            field=models.FloatField(default=5.0, help_text='Federation sync interval in seconds. For Tor: 5-10s (slow but private). For LAN: 0.1-1s (fast). Federation is always slower than local updates.'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='local_poll_interval',
            field=models.FloatField(default=1.0, help_text='Local SSE update interval in seconds. For chat/games: 0.016 (60fps), 0.033 (30fps), 0.1 (10fps). For boards: 1.0 (1fps). Lower = more responsive but higher CPU usage.'),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='use_lan_federation',
            field=models.BooleanField(default=False, help_text='Bypass Tor proxy for LAN/clearnet federation. Enable for local network gaming (10-50ms latency). Disable for privacy/Tor federation (1-5s latency).'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='is_realtime',
            field=models.BooleanField(default=False, help_text='Enable real-time federation sync for low-latency updates. When True, messages bypass BitSync polling and use direct BBS-to-BBS push.'),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='trusted_peers',
            field=models.JSONField(blank=True, default=list, help_text="List of trusted peer onion URLs for real-time sync. Format: ['http://peer1.onion', 'http://peer2.onion'] or ['http://192.168.1.100:8000'] for LAN. Only applies when is_realtime=True."),
        ),
    ]
