# Generated by Django 5.0.6 on 2025-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_privatemessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
