# Generated by Django 5.0.6 on 2025-09-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federation', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationreport',
            name='report_type',
            field=models.CharField(choices=[('message_report', 'Message Report'), ('general_inquiry', 'General Inquiry')], default='message_report', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationreport',
            name='reported_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='messaging.message'),
        ),
    ]
