# Generated by Django 5.0.6 on 2025-10-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who owns and can manage this applet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applet',
            name='author_pubkey',
            field=models.TextField(blank=True, help_text="Public key of the applet's author. Automatically set if an owner is selected."),
        ),
    ]
