# Generated by Django 5.0.6 on 2025-10-02 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applets', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applet',
            name='event_board',
            field=models.ForeignKey(blank=True, help_text='The message board this applet will use for its public events.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.messageboard'),
        ),
        migrations.AddField(
            model_name='applet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applets.appletcategory'),
        ),
        migrations.AddField(
            model_name='appletdata',
            name='applet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_instances', to='applets.applet'),
        ),
        migrations.AddField(
            model_name='appletdata',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applet_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='highscore',
            name='applet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='applets.applet'),
        ),
        migrations.AlterUniqueTogether(
            name='appletdata',
            unique_together={('applet', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='highscore',
            unique_together={('applet', 'owner_pubkey')},
        ),
    ]
