# Generated by Django 5.0.6 on 2025-10-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applets', '0002_applet_owner_alter_applet_author_pubkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applet',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for applet-specific parameters (e.g., asset hashes or required libraries).'),
        ),
    ]
